### ISSUE TITLE
Familiarity with Python libraries

### ISSUE THREAD

**Issue by TinManAkshay** [stm32duino/LSM6DSR#6]
Hi @cparata ,

I want to thank you again to help finding the solutions in our journey throughout the issues. These libraries are working great.

I wanted to reach out this time because its regarding some other project in our company which requires same LSM6 IMU on the PCB. The change is here that we need to use python libraries for the same sensor on Raspberry Pi. 

Are you familiar with any of the python libraries out there in the internet for LSM6? Any info. would be highly appreciated.

Thanks again,
Akshay

**Comment by fpistm** [comment]
Hi @TinManAkshay 
GitHub issue is dedicated for issue with the library. This is not a support or a forum to discuss.
This issue is really not linked to the library not Arduino for STM32.
So I close it.
